sudo: required

branches:
  only:
    - master
    
services:
  - docker

before_install:
  - docker build -t wtjandra96/node-server-test -f ./server/Dockerfile.dev ./server
  # - docker build -t wtjandra96/react-client-test -f ./client/Dockerfile.dev ./client

script:
  # Start server tests
  - docker network create testing-net
  - docker run --name mongo --network=testing-net -d mongo # Need to connect to mongo service for testing
  - docker run --network=testing-net -e JWT_SECRET=$JWT_SECRET wtjandra96/node-server-test npm run test

  # Cleanup
  - docker stop mongo
  - docker rm mongo
  - docker stop wtjandra96/node-server-test
  - docker rm wtjandra96/node-server-test
  - docker network rm testing-net
  

  # Start client tests
  # - docker run -e CI=true wtjandra96/react-client-test npm test
  
  # Cleanup
  - docker stop wtjandra96/react-client-test
  - docker rm wtjandra96/react-client-test