version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - cd server
      - npm install
      - cd ..

  build:
    commands:
      - echo "Entered the build phase"
      - cd server
      - npm run lint
      - npm test
      - cd ..
