version: 0.2

env:
    parameter-store:
      PORT: /CodeBuild/PORT
      JWT_SECRET: /CodeBuild/JWT_SECRET
      DATABASE_URI: /CodeBuild/DATABASE_URI

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - cd server
      - npm install
      - cd ..

  build:
    commands:
      - echo "Entered the build phase"
      - cd server
      - npm run lint
      - npm test
      - cd ..
