version: '3'
services:
  # MongoDB container is only used for testing
  mongo:
    image: mongo
  proxy:
    # Waits for client and api to finish
    depends_on:
      - client
      - api
    # Restarts on exit
    restart: always
    build:
      # Specifices which Dockerfile to use
      dockerfile: Dockerfile.dev
      # Where it resides
      context: ./proxy
    # Enables hot-reload for windows
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:80"
  client:
    # Restarts on exit
    restart: always
    build:
      # Specifices which Dockerfile to use
      dockerfile: Dockerfile.dev
      # Where it resides
      context: ./client
    volumes:
      # Do not share node_modules
      - /app/node_modules
      # Share files for local development
      - ./client:/app
    # Enables hot-reload for windows
    environment:
      - CHOKIDAR_USEPOLLING=true
    # Fix app exit(0) issue on container
    stdin_open: true
  api:
    # Restarts on exit
    restart: always
    # Waits for mongo to finish
    depends_on:
      - mongo
    build:
      # Specifies which Dockerfile to use
      dockerfile: Dockerfile.dev
      #Where it resides
      context: ./server
    volumes:
      # Do not share node_modules
      - /app/node_modules
      # Share files for local development
      - ./server:/app