version: '3'
services:
  react-client:
    build:
      # Specifices which Dockerfile to use
      dockerfile: Dockerfile.dev
      # Where it resides
      context: ./client
    volumes:
      # Do not share node_modules
      - /app/node_modules
      # Share files for local development
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    stdin_open: true
  node-server:
    build:
      # Specifies which Dockerfile to use
      dockerfile: Dockerfile.dev
      #Where it resides
      context: ./server
    volumes:
      # Do not share node_modules
      - /app/node_modules
      # Share files for local development
      - ./server:/app
    ports:
      - "5000:5000"