const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
const SET_CATEGORIES_LIST = "SET_CATEGORIES_LIST";
const CLEAR_CATEGORIES_LIST = "CLEAR_CATEGORIES_LIST";
const UPDATE_CATEGORIES_LIST = "UPDATE_CATEGORIES_LIST";
const REMOVE_CATEGORY = "REMOVE_CATEGORY";
const SET_ERRORS = "SET_ERRORS";
const CLEAR_ERRORS = "CLEAR_ERRORS";
const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export {
  ADD_NEW_CATEGORY,
  SET_CATEGORIES_LIST,
  CLEAR_CATEGORIES_LIST,
  UPDATE_CATEGORIES_LIST,
  REMOVE_CATEGORY,
  SET_ERRORS,
  CLEAR_ERRORS,
  UPDATE_CATEGORY
};
