const SET_USER = "SET_USER"
const CLEAR_USER = "CLEAR_USER"
const AUTHENTICATE = "AUTHENTICATE"
const DEAUTHENTICATE = "DEAUTHENTICATE"
const SET_ERRORS = "SET_ERRORS"
const CLEAR_ERRORS = "CLEAR_ERRORS"
const SET_GUEST = "SET_GUEST"

export {
  SET_USER,
  CLEAR_USER,
  AUTHENTICATE,
  DEAUTHENTICATE,
  SET_ERRORS,
  CLEAR_ERRORS,
  SET_GUEST
}