const SET_USER = "SET_USER"
const CLEAR_USER = "CLEAR_USER"
const AUTHENTICATE = "AUTHENTICATE"
const DEAUTHENTICATE = "DEAUTHENTICATE"
const SET_USER_ERRORS = "SET_USER_ERRORS"
const CLEAR_ERRORS = "CLEAR_ERRORS"
const SET_GUEST = "SET_GUEST"
const START_USER_ACTION = "START_USER_ACTION"
const STOP_USER_ACTION = "STOP_USER_ACTION"

export {
  SET_USER,
  CLEAR_USER,
  AUTHENTICATE,
  DEAUTHENTICATE,
  SET_USER_ERRORS,
  CLEAR_ERRORS,
  SET_GUEST,
  START_USER_ACTION,
  STOP_USER_ACTION
}